/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedCategoriesCategoryIdRouteImport } from './routes/_authenticated/categories/$categoryId'
import { Route as AuthenticatedLoansIndexRouteImport } from './routes/_authenticated/loans/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAiRouteImport } from './routes/_authenticated/settings/ai'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsGmailRouteImport } from './routes/_authenticated/settings/gmail'
import { Route as AuthenticatedSettingsMcpRouteImport } from './routes/_authenticated/settings/mcp'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedTransactionsTransactionIdRouteImport } from './routes/_authenticated/transactions/$transactionId'
import { Route as AuthenticatedTransactionsImportRouteImport } from './routes/_authenticated/transactions/import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoriesCategoryIdRoute =
  AuthenticatedCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLoansIndexRoute = AuthenticatedLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAiRoute = AuthenticatedSettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGmailRoute =
  AuthenticatedSettingsGmailRouteImport.update({
    id: '/settings/gmail',
    path: '/settings/gmail',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsMcpRoute =
  AuthenticatedSettingsMcpRouteImport.update({
    id: '/settings/mcp',
    path: '/settings/mcp',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsTransactionIdRoute =
  AuthenticatedTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsImportRoute =
  AuthenticatedTransactionsImportRouteImport.update({
    id: '/transactions/import',
    path: '/transactions/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$categoryId': typeof AuthenticatedCategoriesCategoryIdRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/gmail': typeof AuthenticatedSettingsGmailRoute
  '/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/transactions/$transactionId': typeof AuthenticatedTransactionsTransactionIdRoute
  '/transactions/import': typeof AuthenticatedTransactionsImportRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/loans/': typeof AuthenticatedLoansIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/categories/$categoryId': typeof AuthenticatedCategoriesCategoryIdRoute
  '/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/gmail': typeof AuthenticatedSettingsGmailRoute
  '/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/transactions/$transactionId': typeof AuthenticatedTransactionsTransactionIdRoute
  '/transactions/import': typeof AuthenticatedTransactionsImportRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/loans': typeof AuthenticatedLoansIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/categories/$categoryId': typeof AuthenticatedCategoriesCategoryIdRoute
  '/_authenticated/settings/ai': typeof AuthenticatedSettingsAiRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/gmail': typeof AuthenticatedSettingsGmailRoute
  '/_authenticated/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/_authenticated/transactions/$transactionId': typeof AuthenticatedTransactionsTransactionIdRoute
  '/_authenticated/transactions/import': typeof AuthenticatedTransactionsImportRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/loans/': typeof AuthenticatedLoansIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/api/$'
    | '/auth/callback'
    | '/categories/$categoryId'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/gmail'
    | '/settings/mcp'
    | '/transactions/$transactionId'
    | '/transactions/import'
    | '/categories/'
    | '/loans/'
    | '/settings/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/api/$'
    | '/auth/callback'
    | '/categories/$categoryId'
    | '/settings/ai'
    | '/settings/appearance'
    | '/settings/gmail'
    | '/settings/mcp'
    | '/transactions/$transactionId'
    | '/transactions/import'
    | '/categories'
    | '/loans'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/api/$'
    | '/auth/callback'
    | '/_authenticated/categories/$categoryId'
    | '/_authenticated/settings/ai'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/gmail'
    | '/_authenticated/settings/mcp'
    | '/_authenticated/transactions/$transactionId'
    | '/_authenticated/transactions/import'
    | '/_authenticated/categories/'
    | '/_authenticated/loans/'
    | '/_authenticated/settings/'
    | '/_authenticated/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories/$categoryId': {
      id: '/_authenticated/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof AuthenticatedCategoriesCategoryIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/': {
      id: '/_authenticated/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AuthenticatedLoansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/ai': {
      id: '/_authenticated/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof AuthenticatedSettingsAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/gmail': {
      id: '/_authenticated/settings/gmail'
      path: '/settings/gmail'
      fullPath: '/settings/gmail'
      preLoaderRoute: typeof AuthenticatedSettingsGmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/mcp': {
      id: '/_authenticated/settings/mcp'
      path: '/settings/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof AuthenticatedSettingsMcpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/$transactionId': {
      id: '/_authenticated/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof AuthenticatedTransactionsTransactionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/import': {
      id: '/_authenticated/transactions/import'
      path: '/transactions/import'
      fullPath: '/transactions/import'
      preLoaderRoute: typeof AuthenticatedTransactionsImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCategoriesCategoryIdRoute: typeof AuthenticatedCategoriesCategoryIdRoute
  AuthenticatedSettingsAiRoute: typeof AuthenticatedSettingsAiRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsGmailRoute: typeof AuthenticatedSettingsGmailRoute
  AuthenticatedSettingsMcpRoute: typeof AuthenticatedSettingsMcpRoute
  AuthenticatedTransactionsTransactionIdRoute: typeof AuthenticatedTransactionsTransactionIdRoute
  AuthenticatedTransactionsImportRoute: typeof AuthenticatedTransactionsImportRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedLoansIndexRoute: typeof AuthenticatedLoansIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCategoriesCategoryIdRoute:
    AuthenticatedCategoriesCategoryIdRoute,
  AuthenticatedSettingsAiRoute: AuthenticatedSettingsAiRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
  AuthenticatedSettingsGmailRoute: AuthenticatedSettingsGmailRoute,
  AuthenticatedSettingsMcpRoute: AuthenticatedSettingsMcpRoute,
  AuthenticatedTransactionsTransactionIdRoute:
    AuthenticatedTransactionsTransactionIdRoute,
  AuthenticatedTransactionsImportRoute: AuthenticatedTransactionsImportRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedLoansIndexRoute: AuthenticatedLoansIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiSplatRoute: ApiSplatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
